from views.activity_view import ActivityView as ActivityView
from views.auth_token_view import AuthTokenView as AuthTokenView
from views.category_view import CategoryView as CategoryView
from views.code_sent_view import CodeSentView as CodeSentView
from views.customer_view import CustomerView as CustomerView
from views.deleted_view import DeletedView as DeletedView
from views.invitation_view import InvitationView as InvitationView
from views.item_view import ItemView as ItemView
from views.lead_view import LeadView as LeadView
from views.link_tree_view import LinkTreeView as LinkTreeView
from views.list_version_view import ListVersionView as ListVersionView
from views.magazine_page_view import MagazinePageView as MagazinePageView
from views.magazine_view import MagazineView as MagazineView
from views.order_item_view import OrderItemView as OrderItemView
from views.order_view import OrderView as OrderView
from views.price_list_view import PriceListView as PriceListView
from views.product_image_view import ProductImageView as ProductImageView
from views.product_view import ProductView as ProductView
from views.public_list_view import PublicListView as PublicListView
from views.public_magazine_view import PublicMagazineView as PublicMagazineView
from views.public_menu_view import PublicMenuView as PublicMenuView
from views.public_tenant_view import PublicTenantView as PublicTenantView
from views.public_viewer_view import PublicViewerView as PublicViewerView
from views.reordered_view import ReorderedView as ReorderedView
from views.tenant_view import TenantView as TenantView
from views.user_view import UserView as UserView
