from views.deleted_view import DeletedView as DeletedView
from views.reordered_view import ReorderedView as ReorderedView
from views.user_view import UserView as UserView
from views.tenant_view import TenantView as TenantView
from views.item_view import ItemView as ItemView
from views.list_version_view import ListVersionView as ListVersionView
from views.price_list_view import PriceListView as PriceListView
from views.auth_token_view import AuthTokenView as AuthTokenView
from views.code_sent_view import CodeSentView as CodeSentView
from views.public_list_view import PublicListView as PublicListView
from views.public_menu_view import PublicMenuView as PublicMenuView
