from models.schema_columns import add_missing_columns


def ensure_tenant_columns() -> None:
    add_missing_columns(
        "tenants",
        [
            ("plan", "plan VARCHAR(16) NOT NULL DEFAULT 'free'"),
            ("plan_gate", "plan_gate INTEGER NOT NULL DEFAULT 0"),
            ("billing_provider", "billing_provider VARCHAR(32)"),
            ("billing_customer_id", "billing_customer_id VARCHAR(64)"),
            ("billing_subscription_id", "billing_subscription_id VARCHAR(64)"),
            ("billing_variant_id", "billing_variant_id VARCHAR(64)"),
            ("billing_status", "billing_status VARCHAR(32)"),
            ("billing_renews_at", "billing_renews_at DATETIME"),
            ("billing_ends_at", "billing_ends_at DATETIME"),
            ("billing_trial_ends_at", "billing_trial_ends_at DATETIME"),
            ("billing_portal_url", "billing_portal_url TEXT"),
            ("billing_update_payment_url", "billing_update_payment_url TEXT"),
            ("billing_card_brand", "billing_card_brand VARCHAR(32)"),
            ("billing_card_last_four", "billing_card_last_four VARCHAR(8)"),
            ("billing_checkout_id", "billing_checkout_id VARCHAR(64)"),
            ("billing_order_id", "billing_order_id VARCHAR(64)"),
            ("billing_sync_started_at", "billing_sync_started_at DATETIME"),
            ("billing_sync_next_at", "billing_sync_next_at DATETIME"),
            ("billing_sync_attempts", "billing_sync_attempts INTEGER NOT NULL DEFAULT 0"),
            ("logo_url", "logo_url TEXT"),
            ("brand_color", "brand_color VARCHAR(9)"),
            ("description", "description TEXT"),
            ("list_design", "list_design VARCHAR(32)"),
            ("list_bg_url", "list_bg_url TEXT"),
            ("list_bg_overlay", "list_bg_overlay INTEGER NOT NULL DEFAULT 0"),
            ("list_hero_color", "list_hero_color VARCHAR(9)"),
            ("social_instagram", "social_instagram TEXT"),
            ("social_facebook", "social_facebook TEXT"),
            ("social_tiktok", "social_tiktok TEXT"),
            ("social_website", "social_website TEXT"),
            ("social_whatsapp", "social_whatsapp VARCHAR(20)"),
            ("leads_enabled", "leads_enabled INTEGER NOT NULL DEFAULT 0"),
            ("language", "language VARCHAR(5) NOT NULL DEFAULT 'es'"),
            ("timezone", "timezone VARCHAR(64) NOT NULL DEFAULT 'America/Montevideo'"),
            ("delivery_enabled", "delivery_enabled INTEGER NOT NULL DEFAULT 0"),
            ("marketplace_enabled", "marketplace_enabled INTEGER NOT NULL DEFAULT 1"),
            ("marketplace_latitude", "marketplace_latitude VARCHAR(32)"),
            ("marketplace_longitude", "marketplace_longitude VARCHAR(32)"),
            ("business_category", "business_category VARCHAR(32)"),
            ("whatsapp_url", "whatsapp_url TEXT"),
            ("website_url", "website_url TEXT"),
            ("instagram_url", "instagram_url TEXT"),
            ("legal_name", "legal_name VARCHAR(255)"),
            ("tax_id", "tax_id VARCHAR(32)"),
            ("address", "address TEXT"),
        ],
    )
